log4r_config:
  loggers:
    - name : test
      level : DEBUG
      trace : 'true'
      outputters:
      - test_log_outputter
    - name : development
      level : DEBUG
      trace : 'true'
      outputters:
      - development_log_outputter
      - stdout_outputter
    - name : staging
      level : INFO
      trace : 'true'
      outputters:
      - staging_log_outputter
    - name : production
      level : WARN
      trace : 'true'
      outputters:
      - production_log_outputter

  outputters:
    - type: StdoutOutputter
      name: stdout_outputter
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern : "[%d] [%l] %m"
        type : PatternFormatter
    - type : FileOutputter
      name : test_log_outputter
      filename: "log/test.log"
      trunc: "true"
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern : "[%d] [%l] %m"
        type : PatternFormatter
    - type : FileOutputter
      name : development_log_outputter
      filename: "log/development.log"
      trunc: "true"
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern : "[%d] [%l] %m"
        type : PatternFormatter
    - type : DateFileOutputter
      name : staging_log_outputter
      dirname: "log"
      filename: "staging.log"
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern : "[%d] [%l] %m"
        type : PatternFormatter
    - type : DateFileOutputter
      name : production_log_outputter
      dirname: "log"
      filename: "production.log"
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern : "[%d] [%l] %m"
        type : PatternFormatter