FixSchedulesJob:
  description: "Add any missing feed update schedules"
  queue: maintenance
  every:
    - "1h"
    - :first_in: "10s"
DestroyOldJobStatesJob:
  description: "Remove old job states from the db"
  queue: maintenance
  every:
    - "1h"
    - :first_in: "10s"
CleanupSignupsJob:
  description: "Discard old signed up but unconfirmed users"
  queue: maintenance
  every:
    - "1d"
    - :first_in: "10m"
