FixSchedulesJob:
  description: "Add any missing feed update schedules"
  queue: maintenance
  every:
    - "1h"
    - :first_in: "10s"
DestroyOldJobStatesJob:
  description: "Remove old job states from the db"
  queue: maintenance
  every:
    - "1h"
    - :first_in: "10s"
CleanupInvitationsJob:
  description: "Discard old unaccepted invitations and reset the per-user daily invitation limit"
  queue: maintenance
  every:
    - "1d"
    - :first_in: "10m"
