# URLs of websites owned by members of the AEDE association from Spain.
# We refuse to aggregate content from them for legal reasons.
aede_urls:
#Grupo Prisa:
  - adnradio.cl
  - alamah.com.mx
  - alfaguara.com
  - alfaguarainfantilyjuvenil.com
  - as.com
  - avaliaeducacional.com.br
  - besame.co.cr
  - besame.fm
  - cadenadial.com
  - cadenaser.com
  - caracol.com.co
  - caracol1260.com
  - cincodias.com
  - cinemania.es
  - colorincolorradio.com
  - concierto.cl
  - continental.com.ar
  - corazon.cl
  - dalealplay.com
  - e-vocacion.es
  - editoraid.com.br
  - editorialaltea.com.mx
  - editorialtaurus.com
  - edusfera.es
  - elboomeran.com
  - elpais.com
  - elpaisaguilar.es
  - fmdos.cl
  - fundacionsantillana.com
  - futuro.cl
  - glrnetworks.com
  - gruposantillanaclientes.es
  - gruposantillanapr.com
  - hjck.com
  - huffingtonpost.es
  - iarc.cl
  - ineverycrea.net
  - iol.pt
  - kebuena.com.mx
  - lavallenata.com
  - librosaguilar.com
  - librosalfaguarainfantil.com
  - librosalfaguarajuvenil.com
  - los40.com
  - m80radio.com
  - maxima.fm
  - mediacapital.pt
  - meristation.com
  - moderna.com.br
  - objetiva.com.br
  - onstage.es
  - oxigeno.fm
  - pasionmanderley.com
  - planeo.pt
  - planetevents.es
  - pluralent.com
  - pluralportugal.pt
  - plus.es
  - prisa.com
  - prisabs.com
  - prisaediciones.com
  - prisaediciones.com/cas
  - prisanoticias.com
  - prisaradio.com
  - prisarevistas.com
  - prisatv.com
  - pudahuel.cl
  - puntodelectura.com
  - pupitreapp.com
  - radioacktiva.com
  - radioactiva.cl
  - radioimagina.cl
  - radiole.com
  - radiopanama.com.pa
  - richmondelt.com
  - rlm.es
  - rockandpop.cl
  - rollingstone.es
  - santillana.co.cr
  - santillana.com
  - santillana.com.ar
  - santillana.com.bo
  - santillana.com.co
  - santillana.com.do
  - santillana.com.ec
  - santillana.com.gt
  - santillana.com.hn
  - santillana.com.mx
  - santillana.com.pa
  - santillana.com.pe
  - santillana.com.py
  - santillana.com.sv
  - santillana.com.uy
  - santillana.com.ve
  - santillana.es
  - santillana.pt
  - santillana.twig-world.es
  - santillanacompartir.cl
  - santillanacompartir.co.cr
  - santillanacompartir.com
  - santillanacompartir.com.ar
  - santillanacompartir.com.co
  - santillanacompartir.com.ec
  - santillanacompartir.com.gt
  - santillanacompartir.com.hn
  - santillanacompartir.com.mx
  - santillanacompartir.com.sv
  - santillanaele.com
  - santillanafrancais.com
  - santillanausa.com
  - sistemauno.com
  - sumadeletras.com
  - surnoticias.cl
  - tareasymas.es
  - tropicanafm.com
  - vacacionessantillana.es
  - wradio.com.co
  - wradio.com.mx
  - wradio690.com
  - xeqradio.mx
#Unidad editorial:
  - 13tv.es
  - actualidadeconomica.es
  - conferenciasyformacion.com
  - correofarmaceutico.com
  - descubrirelarte.es
  - detiendasporelmundo.es
  - diariomedico.com
  - dmedicina.com
  - elcultural.es
  - elmundo.es
  - escuelaunidadeditorial.es
  - esferalibros.com
  - estadiodeportivo.com
  - expansion.com
  - expansionyempleo.com
  - globaliza.com
  - ign.com
  - lastlap.com
  - logintegral.com
  - marca.com
  - marcamotor.com
  - marcamotoranuncios.com
  - metropoli.com
  - ocholeguas.com
  - orbyt.es
  - orbytsmarttv.es
  - telva.com
  - tiramillas.net
  - unidadeditorial.com
  - unidadeditorial.es
  - veo.es
#Grupo Godó:
  - 8tv.cat
  - clasificados.es
  - grupogodo.com
  - grupogodo.net
  - lavanguardia.com
  - mgmagazine.es
  - mundodeportivo.com
  - playboy.es
  - prismapublicaciones.com
  - publipressmedia.com
  - rac1.org
  - rac105.cat
  - yaencontre.com
#Vocento:
  - 11870.com
  - abc.es
  - autocasion.com
  - avanzaentucarrera.com
  - bocaboca.com
  - cadena100.es
  - colpisa.com
  - cope.es
  - diariosur.es
  - diariovasco.com
  - elcomercio.es
  - elcorreo.com
  - eldiariomontanes.es
  - elnortedecastilla.es
  - europroduzione.com
  - finanzas.com
  - hillvalley.es
  - hoy.es
  - ideal.es
  - infoempleo.com
  - kioskoymas.com
  - larioja.com
  - lasprovincias.es
  - laverdad.es
  - lavozdigital.es
  - megastar.fm
  - mujerhoy.com
  - nettv.es
  - pisos.com
  - rockfm.fm
  - tusanuncios.com
  - veralia.com
  - vocento.com
#Grupo Zeta:
  - autohebdosport.es
  - cuorestilo.com
  - diariocordoba.com
  - diariolagrada.com
  - dicom-medios.com
  - digitalcamera.es
  - edicionesb.com
  - elperiodico.com
  - elperiodicodearagon.com
  - elperiodicoextremadura.com
  - elperiodicomediterraneo.com
  - grupozeta.es
  - interviu.es
  - lacronicabadajoz.com
  - mortadeloyfilemon.com
  - primeralinea.es
  - redaragon.com
  - redextremadura.com
  - revistacuore.com
  - sport.es
  - tiempodehoy.com
  - woman.es
  - zetagestion.com
#Grupo Planeta:
  - 10-18.fr
  - 12-21editions.fr
  - a3eventos.es
  - academiadeinteligencia.com.br
  - antena3.com
  - arrobabooks.com
  - atresmediapublicidad.com
  - atresplayer.com
  - belfond.fr
  - casadellibro.com
  - ceac.es
  - chemin-vert-editions.com
  - circulo.es
  - cle-inter.com
  - deaplaneta.com
  - deustoformacion.com
  - deustosalud.com
  - dvdgo.com
  - eae.es
  - editions-acropole.com
  - editions-bordas.fr
  - editions-perrin.fr
  - editions-retz.com
  - editionsfirst.fr
  - editionsladecouverte.fr
  - editis.com
  - editorialplaneta.cl
  - editorialplaneta.com.uy
  - edpeditores.com
  - englishtoday.es
  - europafm.com
  - factoriaprisma.com
  - fleuve-editions.fr
  - grund.fr
  - grup62.cat
  - grupoplanetavenezuela.blogspot.com.es
  - harvard-deusto.com
  - hemma.be
  - home.es
  - horscollection.com
  - interforum.fr
  - kurokawa.fr
  - laffont.fr
  - lanetro.com
  - langueauchat.be
  - larazon.es
  - lasexta.com
  - laudeo.com
  - lerobert.com
  - lesescales.fr
  - lonelyplanet.es
  - lonelyplanet.fr
  - melodia-fm.com
  - nathan.fr
  - nubeox.com
  - nubico.es
  - obs-edu.com
  - omnibus.tm.fr
  - ondacero.es
  - paraschool.com
  - placedesediteurs.com
  - planeta-junior.com
  - planeta.es
  - planeta.pt
  - planetadeagostini.es
  - planetadelibros.com
  - planetadelibros.com.mx
  - planetadelivros.com.br
  - planetadirecto.com
  - planetasaber.com
  - plon.fr
  - pocket.fr
  - pocketjeunesse.fr
  - pressesdelacite.com
  - prismapublicaciones.com
  - publishers-square.com
  - shopo.tv
  - solar.fr
  - sonatine-editions.fr
  - superpadres.com
  - tiendarealmadrid.com
  - ulisesinteractive.com
  - unibarcelona.com
  - viu.es
  - xoeditions.com
#Grupo Voz:
  - canalvoz.com
  - escuelademedios.com
  - fundacionsantiagoreyfernandezlatorre.com
  - lavozdegalicia.com
  - lavozdegalicia.es
  - prensaescuela.es
  - radiovoz.com
  - sondaxe.es
  - vozaudiovisual.es
  - voznatura.com
  - vtelevision.es
#Editorial Prensa Ibérica:
  - agaprint.com
  - agmprint.com
  - albaeditorial.es
  - allisonandbusby.com
  - clubinformacion.com
  - diaridegirona.cat
  - diariodeibiza.es
  - diariodemallorca.es
  - diarioinformacion.com
  - distribucionespapiro.com
  - emporda.info
  - epi.es
  - estadiodeportivo.com
  - farodevigo.es
  - imprintsa.com
  - informaciontv.es
  - la-provincia.com
  - la977.com
  - laopinion.es
  - laopinioncoruna.es
  - laopiniondemalaga.es
  - laopiniondemurcia.es
  - laopiniondezamora.es
  - laprovincia.es
  - lavanguardia.com
  - levante-emv.com
  - levantetv.es
  - lne.es
  - mallorcazeitung.es
  - radio-canarias.es
  - radiodiarioibiza.es
  - regio7.cat
  - renr.es
  - superdeporte.es
  - totaldis.com
  - tribunadegirona.com
  - valdisme.es
  - vilarroya.com
#Grupo Heraldo:
  - 3tcontrol.com
  - distridasa.com
  - factoriaplural.es
  - gabesa.es
  - grupoheraldo.com
  - heraldo.es
  - heraldodesoria.es
  - hiberus.com
  - impresanorte.es
  - methagestion.es
  - ztv.es
#Grupo La información:
  - brandok.es
  - chofert.com
  - conocernavarra.com
  - definde.com
  - diariodenavarra.es
  - dnclasificados.com
  - egn.es
  - funtasticclub.es
  - kinetical.com
  - lainformacion.es
  - mynews.es
  - redcomiendo.com
#Grupo Serra:
  - clubdelsuscriptor.com
  - dbalears.cat
  - flaixmallorca.com
  - gruposerra.com
  - luxmallorca.tv
  - majorcadailybulletin.com
  - mallorcamagazin.com
  - menorca.info
  - novatelevisio.com
  - ofertasenmallorca.com
  - periodicodeibiza.es
  - setmanarisoller.cat
  - ultimahora.es
  - ultimahoraclasificados.com
  - ultimahoraradio.es
  - uponthewall.es
  - vestimallorca.com
#Grupo Joly:
  - diariodecadiz.es
  - diariodejerez.es
  - diariodesevilla.es
  - elalmeria.es
  - eldiadecordoba.es
  - europasur.es
  - granadahoy.com
  - grupojoly.com
  - huelvainformacion.es
  - malagahoy.es
#Grupo Noticias:
  - deia.com
  - noticiasdealava.com
  - noticiasdegipuzkoa.com
  - noticiasdenavarra.com
#Grupo Promecal:
  - agenciaical.es
  - cerescg.com
  - diariodeavila.es
  - diariodeburgos.es
  - diariopalentino.es
  - eladelantado.com
  - eldiadevalladolid.com
  - latribunadealbacete.es
  - latribunadeciudadreal.es
  - latribunadecuenca.es
  - latribunadetoledo.es
  - natv.es
  - promecal.es
  - revistaosaca.com
  - rtvcyl.es
  - serviciosdeprensa.com
  - tallerdeimpresion.com
  - viveradio.es
#Editorial EcoPrensa:
  - economiahoy.mx
  - editorialecoprensa.es
  - eleconomista.es
  - eleconomistaamerica.cl
  - eleconomistaamerica.co
  - eleconomistaamerica.com
  - eleconomistaamerica.com.ar
  - eleconomistaamerica.com.br
  - eleconomistaamerica.pe
#Grupo El Progreso:
  - axencia.com
  - galiciae.com
  - lugopress.com
  - telelugo.tv
#Edigrup Media:
  - castillayleonesradio.es
  - diariodeleon.es
  - diariodesoria.es
  - diariodevalladolid.es
  - edigrup.es
  - elcorreodeburgos.com
#Others:
  - aede.es
  - canarias7.es
  - cm2000.es
  - diaridetarragona.com
  - diarideterrassa.es
  - diariodelaltoaragon.es
  - diariojaen.es
  - eladelantado.com
  - eladelantado.tv
  - elcorreoweb.es
  - lagacetadesalamanca.es
  - lavozdealmeria.es
